export * from './Login/LoginPage'
export * from './Home/HomePage'
export * from './Citizen/CitizenPage'
export * from './Service/ServicePage'
export * from './Service/ServiceCreatedPage'
export * from './Contact/ContactPage'
export * from './Protocol/ProtocolPage'
export * from './Dashboard/DashboardPage'
